version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_USER: tomas
      MYSQL_PASSWORD: tomas
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqlDB
    ports:
      - "3306:3306"
    volumes:
      - ./sql-data/db:/var/lib/mysql