version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_USER: grupo4
      MYSQL_PASSWORD: grupo4
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tpDB
    ports:
      - "3306:3306"
    volumes:
      - ./sql-data/db:/var/lib/mysql